### ISSUE TITLE
Cooperation

### ISSUE THREAD

**Issue by sgiannino** [Team-Silver-Sphere/SquadJS#1]
Hi! I would like to give a contribute to this project! I usually play squad and i use Node at work :dango: 
Feel free to add me on discord enkos#7573

**Comment by Thomas-Smyth** [comment]
Hello @Enkosz,

I am just beginning a big rewriting, so it might be hard to collaborate to start with while I get my initial ideas down.

Regardless, if you PM me (Tommy™#0296) then we can have a discussion and see how we can collaborate and/or share workloads.
