### ISSUE TITLE
Round winner - Showing wrong map

### ISSUE THREAD

**Issue by gonzalo658** [Team-Silver-Sphere/SquadJS#105]
Hi, 

Seems that my round winner shows the "next" map instead of the map that was played. 
Cant explain it more then that. Hit me up if you need more info 👍

**Comment by hippalectryon-0** [comment]
#114

**Comment by LeventHAN** [comment]
> Hi,
> 
> Seems that my round winner shows the "next" map instead of the map that was played.
> Cant explain it more then that. Hit me up if you need more info 👍

This issue was fixed on v2, however: 

> #114

This PR has nothing to do with the showing the NEXT map 😄 but this is fix for a SquadJSv2 bug that was showing the PREVIUS layer where it sould show the current one. lol 
But like I mentioned this issue has been fixed on v2 for sure 💯

**Comment by hippalectryon-0** [comment]
oops x) my bad

**Comment by gonzalo658** [comment]
So, this will not work for my problem i guess?

**Comment by LeventHAN** [comment]
> So, this will not work for my problem i guess?

Well it will if you upgrade to V2, but I don't recommend you to upgrade now.
Please wait for the SquadJS v2 release 👍

**Comment by gonzalo658** [comment]
Any hotfix for this avalible ?

**Comment by Thomas-Smyth** [comment]
Fixed in SquadJS v2.
