### ISSUE TITLE
Multi Server Question

### ISSUE THREAD

**Issue by werewolfboy13** [Team-Silver-Sphere/SquadJS#115]
So If I am going to deploy this on another box with to servers how is that going to work? Can it be on the same bot token that the first server is using or does it have to be another box. Also if the bot allows if how will I go about using it for two servers, mostly team-kill and admin cam on both?

**Comment by LeventHAN** [comment]
- You have 1 dedi server with 2 Squad Game Servers running on it.
    - > You will not need 2 SquadJS instance. One is going to run both. But you will need to put your multi servers on the DB...
    - > One discord bot token is enough SquadJS handles the rest.
    
 - You have 2 dedicated servers with seperate each running 1 Squad Game Server
    - > You will need 2 SquadJS instances on EACH dedi server.
    - > You will need to have the same data for both SquadJS but where it says server you will need to write 2 (See config for more details)
    - > One bot token (use the same for both.)
    
 I hope this will help you 👍 in case I did forget something @Thomas-Smyth is going to correct me since he is the lead dev.

**Comment by werewolfboy13** [comment]
So this is how it is currently. Our newest server is running a Squad.js. Our other Squad Server box is has two other instances running on it. That's is what I am wanting to run it on once we are done testing things. I was wondering how the config will work for that.

**Comment by LeventHAN** [comment]
> So this is how it is currently. Our newest server is running a Squad.js. Our other Squad Server box is has two other instances running on it. That's is what I am wanting to run it on once we are done testing things. I was wondering how the config will work for that.

Join our discord once things are ready and we will be happy to help you :)

**Comment by werewolfboy13** [comment]
oh nice I was looking for it!

**Comment by Thomas-Smyth** [comment]
For SquadJS v1, you should install SquadJS twice on the server, i.e. in two separate folders. You may copy the config across between the two installations, however, you will need to reconfigure the `server` section of the config in order to connect to the other Squad server. It is important that you increase the server's `id` field in the config so that the two servers can be distinguished by the plugins. If using the `mysql-log` plugin you must also insert the new server into the `Servers` table as instructed in the installation guide. All connector configurations may remain the same.

Our Discord: https://squadjs.thomas-smyth.uk/discord

**Comment by werewolfboy13** [comment]
I am using the beta branch rn. I am in the discord.

**Comment by Thomas-Smyth** [comment]
In which case it's much simpler. Install SquadJS once, copy the config and rename it, reconfigure the `server` section of the config and then run SquadJS specifying the config filename, i.e. `node index.js ./config-1.json`. You should still change the server's ID, but there's no need to insert the additional server into the DB for SquadJS v2.

**Comment by werewolfboy13** [comment]
Will this work on the second server 2 instances with the same bot token. What will be the startup command?

**Comment by Thomas-Smyth** [comment]
Yes, you can use the same Discord token for both bots.

The startup command would be `node index.js ./filename.json` where filename is the name of the config file for that server you are looking to start.

**Comment by werewolfboy13** [comment]
so can I do `node index.js ./filename.json ./filename2.json` to start for both servers?

**Comment by Thomas-Smyth** [comment]
No, just run `node index.js ./filename.json` twice, once for each server.

**Comment by werewolfboy13** [comment]
ok Thank you!
