### ISSUE TITLE
!squadjs restartsubsystem logparser is allowing unauthroized user to run the command

### ISSUE THREAD

**Issue by werewolfboy13** [Team-Silver-Sphere/SquadJS#116]
### Description of Issue
When we run the command `!squadjs restartsubsystem logparser` a unauthorized user is able to run the command.

### Errors or Screenshots of Issue

![image](https://user-images.githubusercontent.com/43587009/103443970-5d574700-4c8e-11eb-89c6-19f5e3c7f98b.png)

`      "plugin": "DiscordSubsystemRestarter",
      "enabled": true,
      "discordClient": "discord",
      "role": "794603603317751838"
`

### Squad Information
 * SquadJS Version: beta branch
 * Squad Version: current v1

### System Information
 * Operating System: 10
 * NodeJS Version: 12.19.1
 * Yarn Version: latest

**Comment by LeventHAN** [comment]
Fixed in: https://github.com/Thomas-Smyth/SquadJS/pull/117
