### ISSUE TITLE
AutoKickUnassigned is still kicking admins

### ISSUE THREAD

**Issue by werewolfboy13** [Team-Silver-Sphere/SquadJS#124]
### Description of Issue

The auto AutoKickUnassigned is not ignoring admins.

### Errors or Screenshots of Issue

Config:

      "plugin": "AutoKickUnassigned",
      "enabled": true,
      "warningMessage": "Join a squad, you are are unassigned and will be kicked",
      "kickMessage": "Unassigned - automatically removed",
      "frequencyOfWarnings": 60,
      "unassignedTimer": 300,
      "playerThreshold": 93,
      "roundStartDelay": 900,
      "ignoreAdmins": true,
      "ignoreWhitelist": false

`    // Custom Permissions here for admins.`
`    this.admins = server.getAdminsWithPermission('forceteamchange');`
`    this.whitelist = server.getAdminsWithPermission('reserve');`

I had to change the custom permission. Nothing I change keeps the admins from being kicked.

### Squad Information
 * Plugins in Use: 
 * SquadJS Version: beta brance
 * Squad Version: current

### System Information
 * Operating System: windows server 2019
 * NodeJS Version: current
 * Yarn Version: current

**Comment by werewolfboy13** [comment]
Issue doesn't appear to be fixed.

**Comment by SeanWalsh95** [comment]
set `AutoKickUnassigned` verbose to 2, is it even identifying the admins?

**Comment by werewolfboy13** [comment]
![image](https://user-images.githubusercontent.com/43587009/104379067-223cf980-5553-11eb-9f8a-7437e678c82e.png)
this is a reload. all it shows

**Comment by werewolfboy13** [comment]
![image](https://user-images.githubusercontent.com/43587009/104379115-32ed6f80-5553-11eb-88f3-1cdfd505f9a4.png)

**Comment by werewolfboy13** [comment]
![image](https://user-images.githubusercontent.com/43587009/104379282-78aa3800-5553-11eb-85cd-9f3fd3c3d476.png)
![image](https://user-images.githubusercontent.com/43587009/104379302-7e078280-5553-11eb-8aaf-5529b6587684.png)

**Comment by SeanWalsh95** [comment]
seems to be pulling the admins, looking to see if the plugin is actually logging admins something like `Admin is Unassigned: <playername>`

**Comment by werewolfboy13** [comment]
waiting for the kick now. Also on another note the bot is still warning after a player joins a squad.

**Comment by SeanWalsh95** [comment]
yeah it can do that up to one cycle, it always checks before a kick

**Comment by werewolfboy13** [comment]
`[AutoKickUnassigned][2] Warning: werewolfboy13♪ (AFO) (05:00)`

all it says so far is this

**Comment by SeanWalsh95** [comment]
ok so it seems it's not recognizing them as an admin, ill have to look into it further

**Comment by werewolfboy13** [comment]
![image](https://user-images.githubusercontent.com/43587009/104381591-ead04c00-5556-11eb-81b1-48628e43d4d4.png)

**Comment by werewolfboy13** [comment]
issue appears to be fixed.
![image](https://user-images.githubusercontent.com/43587009/104388382-40aaf100-5563-11eb-8939-36641b5781ec.png)
Closing ticket: Thanks for fixing.
