### ISSUE TITLE
SCBL plugin crash

### ISSUE THREAD

**Issue by werewolfboy13** [Team-Silver-Sphere/SquadJS#128]
### Description of Issue

SCBL plugin causes crashes.

### Errors or Screenshots of Issue

file:///C:/Users/Administrator/Desktop/Servers/Spaghetti-Bot/squad-server/plugins/scbl-info.js:95
    if (data.steamUser.reputationPoints < this.options.threshold)
                       ^

TypeError: Cannot read property 'reputationPoints' of null
    at SCBLInfo.onPlayerConnected (file:///C:/Users/Administrator/Desktop/Servers/Spaghetti-Bot/squad-server/plugins/scbl-info.js:95:24)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

### Squad Information
 * Plugins in Use: 
 * SquadJS Version: current beta branch
 * Squad Version: 1.0

### System Information
 * Operating System: server 2016
 * NodeJS Version: current
 * Yarn Version: currnet

**Comment by werewolfboy13** [comment]
As a note to anyone that has this issue, you can use node.js v12.19.1 as a workaround.

**Comment by Thomas-Smyth** [comment]
Fixed in https://github.com/Thomas-Smyth/SquadJS/commit/f2717e0f629f2366d72b347e11ae364a1c1a32a3.
