### ISSUE TITLE
SCBL Plugin is not following the "threshold" before sending the discord message

### ISSUE THREAD

**Issue by werewolfboy13** [Team-Silver-Sphere/SquadJS#131]
### Description of Issue

scbl is not following the `      "threshold": 6` setting that is in the config.

### Errors or Screenshots of Issue

      "plugin": "SCBLInfo",
      "enabled": true,
      "discordClient": "discord",
      "channelID": "797953382529630258",
      "threshold": 6

![image](https://user-images.githubusercontent.com/43587009/104671925-f3688400-5708-11eb-8a97-93c419894fda.png)

From what I am understanding from the code, https://github.com/Thomas-Smyth/SquadJS/blob/6f2c9507e35c7e105e37a30258a846705bf6637b/squad-server/plugins/scbl-info.js#L101 it doesn't appear to be checking the threshold.

### Squad Information
 * Plugins in Use: 
 * SquadJS Version: current beta branch
 * Squad Version:

### System Information
 * Operating System: server 2019
 * NodeJS Version: v12.19.1
 * Yarn Version: current

**Comment by Thomas-Smyth** [comment]
It's checking it and logging it, but I missed the return call to end the execution of the function so it carries on anyway, whoops.

**Comment by Thomas-Smyth** [comment]
Fixed in https://github.com/Thomas-Smyth/SquadJS/commit/a5f35d5915a5308c1ce01dcad19ba885f5ce1f37

**Comment by werewolfboy13** [comment]
So I was close to what the problem was :). I thought it might have been something like that.
