### ISSUE TITLE
Player IP Collection

### ISSUE THREAD

**Issue by Thomas-Smyth** [Team-Silver-Sphere/SquadJS#132]
### What is the issue, e.g. map voting, you would like to solve?
It would be helpful to get the IPs of players that are connected to a Squad server to allow admins to possibly:
 * IP ban players that could be using multiple accounts to evade bans.
 * Use geolocation to find the **rough** location of a player for analytic purposes, etc.
 * Gain a stronger form of identification to allow admins to report players conducting illegal behaviour to law enforcement, and where possible with the appropriate jurisdiction.

### How would you like us to solve this issue?
My thoughts on a possible solution:
 * Monitor a list of IPs connected to the game server's port.
 * When a new one has detected insert this into a queue.
 * When the next player has connected go through this queue to find a relatively recent IP connection.
 * Assign that IP to the player's stored data.

Concerns:
 * This will only work on servers we can run commands to gain the connection information from, so not rented instances.
 * How do we observe when new IPs connect? Do we poll netstat? If so, what frequency is appropriate?
 * Can we be sure that IP connections to that port will occur in the same order as the player connecting? I.e. if player A then player B connect to the port can we be sure that player A's connection to the Squad server will be detected in SquadJS prior to player B's connection to the server being detected in SquadJS.

**Comment by fantinodavide** [comment]
This is resolved with https://github.com/Team-Silver-Sphere/SquadJS/pull/318
Squad v7.0 replaced the Steam connection manager with EOS, which also introduced logging of players' IPs
