### ISSUE TITLE
add HTTP API in SquadJS v2.0

### ISSUE THREAD

**Issue by ghost** [Team-Silver-Sphere/SquadJS#133]
add HTTP API in SquadJS v2.0
Use http api to execute commands
Easier development for other languages
PHP RCON cannot get the player list

**Comment by SeanWalsh95** [comment]
[restify](http://restify.com) might be useful for this

**Comment by LeventHAN** [comment]
This feature request has been completed see: https://github.com/Thomas-Smyth/SquadJS/pull/158

**Comment by LeventHAN** [comment]
A guide on how to use Socket.IO in integration with the plugin inside SquadJS (SocketIOAPI)

### Video Explanation (For Visual Learners)
https://www.youtube.com/watch?v=HZWmrt3Jy10
### Written simple;
#### Installation CLIENT
 1. Use NPM or YARN to install **socket.io-client** inside your project. (Video example: )
    - Using NPM: <pre><code>npm i socket.io-client</code></pre>
    - Using YARN <pre><code>yarn add socket.io-client</code></pre>
#### Client Initialization
1. the **<script>** import
```js 
<script src="/socket.io/socket.io.js"></script>
```
2. NPM/YARN
```js

// ES6 import or TypeScript
import  { io } from "socket.io-client";
const socket = io.connect('ws://IP:PORT', {
    auth: {
      token: "MySecretPassword"
    }
  })
    
// CommonJS
const io = require("socket.io-client");
const socket = io.connect('ws://IP:PORT', {
  auth: {
    token: "MySecretPassword"
  }
})
```

#### Simple Example Of Usage
```js
// Build in connection error handler in case you want to know if there is any issue
socket.on("connect_error", (err) => {
  console.log(err.data); // { content: "Please retry later" }
});

// When we have a succesfull connection
socket.on("connect", () => {
    // Will return the current player list with squadnames, and side names 
    socket.emit("players", (response) => {
      console.log(response); // Shows a list of players.
    });
    // Will return the player info by SteamID (1 argument)
    socket.emit("getPlayerBySteamID", "My Steam UID",(response) => {
      console.log(response); // Returns the player info by his STEAM64ID 
    });
    // Will warn someone by steamID (2 arguments)
    socket.emit("rcon.warn", "My Steam UID", "My Reason Goes Here",(response) => {
      console.log(response); // This is an option since warn is not returning anything.
    });
});
```

**Comment by ghost** [comment]
> 关于如何将Socket.IO与SquadJS（SocketIOAPI）内的插件集成在一起的指南
> 
> ### 视频说明（面向视觉学习者）
> https://www.youtube.com/watch?v=HZWmrt3Jy10
> 
> ### 文字简单；
> #### 安装客户端
> 1. 使用NPM或YARN在您的项目中安装**socket.io-client**。（视频示例：）
>    
>    * 使用NPM： ```
>      npm i socket.io-client
>      ```
>    * 使用YARN ```
>      yarn add socket.io-client
>      ```
> 
> #### 客户初始化
> 1. 该**<SCRIPT>**进口
> 
> ```js
> <脚本 src = “ /socket.io/socket.io.js” > < /脚本>
> ```
> 
> 1. NPM /纱
> 
> ```js
> //
> 从“ socket.io-client”导入  ES6或TypeScript import {  io  }  ；const socket = io 。connect （'ws：// IP：PORT' ，{ auth：{令牌：“ MySecretPassword” } } ） 
>     
>     
>       
>     
>   
>     
> // CommonJS 
> const  io  =  require （“ socket.io-client” ）; 
> const  socket  =  io 。connect （'ws：// IP：PORT' ， { 
>   auth：{
>     令牌：“ MySecretPassword” 
>   } 
> } ）
> ```
> 
> #### 使用的简单示例
> ```js
> //内置连接错误处理程序，以防您想知道
> 套接字是否存在问题。上（“connect_error” ，（  ERR ）=> {控制台。登录（ERR 。数据）; // {内容： “请稍后再试”} } ）;  
>    
> 
> 
> //当我们有一个成功的全连接
> 套接字时。对（“连接” ， （） =>  { 
>     //将返回当前球员名单
>     插座。EMIT （“玩家” ， （反应） =>  {
>       控制台。登录（响应）;  //显示了球员名单
>     } ）; 
>     //将返回SteamID玩家信息（1个参数）
>     插槽。EMIT （“getPlayerBySteamID” ，“ 我的蒸汽UID” ，（回应） =>  {
>       控制台。日志（响应）;  //通过其STEAM64ID 
>     } ）返回玩家信息；
>     //将通过steamID（2个参数）
>     socket警告某人。EMIT （“警告” ， “我的蒸汽UID” ， “我的原因而在这里” ，（响应） =>  {
>       控制台。登录（响应）;  //这是因为警告没有返回任何一个选项。
>     } ）; 
>     / *
>     //这不在SQUADJS上，但将很快可用。
>     socket.emit（“ rcon.getPlayersV2”，（response）=> { 
>       console.log（response）; //返回高级球员列表，包括边名和球队名称，teamID，球队ID，球员名称，球队规模，球队锁定状态
>     } ）; 
>     * / 
> } ）;
> ```

Thanks

**Comment by LeventHAN** [comment]
@axuanfeng I did update the `warn` by `rcon.warn`
basicly you can just use the avaible methods of SquadJS by just writing them :)
The plugin is avaible at beta. Just update and activate it and test what you can do 👍
