### ISSUE TITLE
Additional Variables for Map Voting

### ISSUE THREAD

**Issue by MadhouseAU** [Team-Silver-Sphere/SquadJS#14]
### What is the issue, e.g. map voting, you would like to solve?
We've trialed your map voting plugin on a live public server. It works as is but requires some more variables to prevent abuse of this plugin by players in-game.

### How would you like us to solve this issue?
Addition of the following variables:
- Minimum number of votes before a map vote is successful & sets next map
- Minimum number of players on server before a map vote is allowed
- Lock in a vote (once a player votes for a map during a round, they cannot change their vote)

### Is there any alternative solutions you can think of?
nil

### Additional Info
nil

**Comment by MadhouseAU** [comment]
Hi @Thomas-Smyth 

Any update on adding these variables?

**Comment by Thomas-Smyth** [comment]
@BigDGaming yes these will be coming, but I need to do a more major rework to mapvoting. I will add these at the same time.

**Comment by Thomas-Smyth** [comment]
Released: https://github.com/Thomas-Smyth/SquadJS/releases/tag/v1.0.10
