### ISSUE TITLE
bug - squad-server/index.js

### ISSUE THREAD

**Issue by ghost** [Team-Silver-Sphere/SquadJS#155]
squad-server/index.js

`334 - const nextMapToBeVoted = nextMap === 'To be voted';`
->
`334 - const nextMapToBeVoted = nextMap.level === 'To be voted';`

**Comment by werewolfboy13** [comment]
What caused this to occur?

**Comment by ghost** [comment]
Voted

**Comment by LeventHAN** [comment]
> squad-server/index.js
> 
> `334 - const nextMapToBeVoted = nextMap === 'To be voted';`
> ->
> `334 - const nextMapToBeVoted = nextMap.level === 'To be voted';`

Can you write more info about this issue please?
How did this occure? Did you chang anything? Which version do you use? Does this issue still occure after the upgrade to current version?

**Comment by ghost** [comment]
v2.0.4
There will be an error when the server turns on map voting

**Comment by LeventHAN** [comment]
> v2.0.4
> There will be an error when the server turns on map voting

So let's say mapvoting is STILL ON PROGRESS and you are manually changing the map to another one and this leaves the value of *nextMap.level* unchanged which stays on `to be voted`. 
Did I understand correctly?

**Comment by ghost** [comment]
squad-server/index.js
`334 - const nextMapToBeVoted = nextMap === 'To be voted';`
nextMap = `{level: 'xxx', layer: 'xxx'}`

`nextMap === 'To be voted';` 
Unable to get map

**Comment by Move2win** [comment]
> > v2.0.4
> > There will be an error when the server turns on map voting
> 
> So let's say mapvoting is STILL ON PROGRESS and you are manually changing the map to another one and this leaves the value of _nextMap.level_ unchanged which stays on `to be voted`.
> Did I understand correctly?

What XuanFeng means is we enabled the OWI official map voting function on our Squad server and using SquadJS.

That is the time when this error occurred.
