### ISSUE TITLE
PlaceHolder Plugin Not following command correctly

### ISSUE THREAD

**Issue by werewolfboy13** [Team-Silver-Sphere/SquadJS#157]
### Description of Issue
Placeholder Command is sending in all comments

### Errors or Screenshots of Issue

![image](https://user-images.githubusercontent.com/43587009/110035706-9a2cd200-7d01-11eb-8656-832d462323c5.png)

### Squad Information
 * Plugins: 
 * SquadJS Version: beta current
 * Squad Version: current

If potentially relevant, please provide regarding the state of the Squad server at the time of error, e.g. the current layer.

### System Information
 * Operating System: N/A
 * NodeJS Version: Current
 * Yarn Version: N/A

**Comment by LeventHAN** [comment]
Fixed with https://github.com/Thomas-Smyth/SquadJS/pull/158/commits/ce53d33b1e7a84f84497442711b580cd16740161 
Will look to one channel (*config.json/channelID*) and only answer if the command is used (*!placeholder* or whatever)

**Comment by 11TStudio** [comment]
> Will look to one channel and only answer if the command is used (!placeholder or whatever)
