### ISSUE TITLE
!subscribe Command is not differentiating servers

### ISSUE THREAD

**Issue by werewolfboy13** [Team-Silver-Sphere/SquadJS#182]
### Description of Issue
When using the `!subscribe` command it does not update the layers correctly. Causing them to update all servers in one embed.

### Errors or Screenshots of Issue
![image](https://user-images.githubusercontent.com/43587009/111202623-1345e800-8592-11eb-8a34-7c1f2d614741.png)

**Comment by werewolfboy13** [comment]
uhhhh ok, wasnt expecting that to show in here lol

**Comment by werewolfboy13** [comment]
New error: 

[DiscordServerStatus][1] Generating message content for update...
DatabaseError [SequelizeDatabaseError]: SQLITE_ERROR: no such column: server
    at Query.formatError (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sequelize\lib\dialects\sqlite\query.js:415:16)
    at Query._handleQueryResponse (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sequelize\lib\dialects\sqlite\query.js:72:18)
    at afterExecute (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sequelize\lib\dialects\sqlite\query.js:246:27)
    at Statement.errBack (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sqlite3\lib\sqlite3.js:14:21) {
  parent: [Error: SQLITE_ERROR: no such column: server] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'SELECT `id`, `channelID`, `messageID`, `server` FROM `DiscordServerStatus_SubscribedMessages` AS `DiscordServerStatus_SubscribedMessage`;'
  },
  original: [Error: SQLITE_ERROR: no such column: server] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'SELECT `id`, `channelID`, `messageID`, `server` FROM `DiscordServerStatus_SubscribedMessages` AS `DiscordServerStatus_SubscribedMessage`;'
  },
  sql: 'SELECT `id`, `channelID`, `messageID`, `server` FROM `DiscordServerStatus_SubscribedMessages` AS `DiscordServerStatus_SubscribedMessage`;',
  parameters: undefined
}

**Comment by Thomas-Smyth** [comment]
> New error:
> 
> [DiscordServerStatus][1] Generating message content for update...
> DatabaseError [SequelizeDatabaseError]: SQLITE_ERROR: no such column: server
> at Query.formatError (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sequelize\lib\dialects\sqlite\query.js:415:16)
> at Query._handleQueryResponse (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sequelize\lib\dialects\sqlite\query.js:72:18)
> at afterExecute (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sequelize\lib\dialects\sqlite\query.js:246:27)
> at Statement.errBack (C:\Users\Administrator\Desktop\Servers\Spaghetti-Bot\node_modules\sqlite3\lib\sqlite3.js:14:21) {
> parent: [Error: SQLITE_ERROR: no such column: server] {
> errno: 1,
> code: 'SQLITE_ERROR',
> sql: 'SELECT `id`, `channelID`, `messageID`, `server` FROM `DiscordServerStatus_SubscribedMessages` AS `DiscordServerStatus_SubscribedMessage`;'
> },
> original: [Error: SQLITE_ERROR: no such column: server] {
> errno: 1,
> code: 'SQLITE_ERROR',
> sql: 'SELECT `id`, `channelID`, `messageID`, `server` FROM `DiscordServerStatus_SubscribedMessages` AS `DiscordServerStatus_SubscribedMessage`;'
> },
> sql: 'SELECT `id`, `channelID`, `messageID`, `server` FROM `DiscordServerStatus_SubscribedMessages` AS `DiscordServerStatus_SubscribedMessage`;',
> parameters: undefined
> }

You'll need to delete your old SQLite file first,

**Comment by LeventHAN** [comment]
@werewolfboy13 is this issue resolved?

**Comment by Thomas-Smyth** [comment]
I think this was resolved, closing.
