### ISSUE TITLE
failed at step 5 run node index.js

### ISSUE THREAD

**Issue by kck1121** [Team-Silver-Sphere/SquadJS#186]
E:\>node index.js
(node:22828) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

im having this problem while trying to set up. terminal gives me this error message when i run node index.js, can u help me how to solve this? thank you!

**Comment by milutinke** [comment]
Which Node version are you using and have you installed Squad JS using yarn?
If you are using Node 15, switch to Node 14.0.0 LTS

**Comment by werewolfboy13** [comment]
If the path above is what you are in are you in the correct folder as well?

**Comment by Thomas-Smyth** [comment]
Please don't delete the template - it's there to ensure all the relevant information needed to debug an issue is provided, which clearly hasn't happened here.

Closing the issue as it seems stale.
