### ISSUE TITLE
Bug in player-disconnect log-parser rule

### ISSUE THREAD

**Issue by cynobill** [Team-Silver-Sphere/SquadJS#194]
Current regex does not match player disconnect log entries. It is missing some white space, this one works...

/^\[([0-9.:-]+)]\[([ 0-9]*)]LogEasyAntiCheatServer: \[[0-9:]+] \[[A-z]+] \[EAC Server] \[Info] \[UnregisterClient] Client: ([A-z0-9]+) PlayerGUID: ([0-9]{17})/

**Comment by LeventHAN** [comment]
This has been already fixed...
But I believe with the roll back it got bugged back @Thomas-Smyth @milutinke ? Or is this not the case?

**Comment by Thomas-Smyth** [comment]
Not sure whether the rollback would have broken it - I think this change was done multiple versions before where the rollback was to. It could have changed without reason again though given that's what broke it in the first place.

Could also be a Windows vs Linux thing. What OS are you using @cynobill?

_As a side note, the above is exactly the reason why issues templates are a thing - to get the information we likely need to debug an issue. Please don't remove them in the future._

**Comment by milutinke** [comment]
Fixed in #190 #191
