### ISSUE TITLE
Our SquadJS has stopped working

### ISSUE THREAD

**Issue by Thagoden** [Team-Silver-Sphere/SquadJS#195]
Hi, this is the error we are getting for our SquadJS.

Error:  node:internal/process/promises:227Error:            triggerUncaughtException(err, true /* fromPromise */);Error:            ^Error:  Error:  Error: read ECONNRESETError:      at TCP.onStreamRead (node:internal/stream_base_commons:211:20)Error:  Emitted 'error' event on FTPTail instance at:Error:      at FTPTail.fetchLoop (file:///ugcc/Installer-Server-Path/6/376/node_modules/ftp-tail/index.js:117:14)Error:      at processTicksAndRejections (node:internal/process/task_queues:94:5) {Error:    errno: -104,Error:    code: 'ECONNRESET',Error:    syscall: 'read'Error:  

I have no experience with any of this kind of stuff, so any help is appreciated.

**Comment by Thagoden** [comment]
I believe it may be an issue when the server is not restarted.  This is only a thought as yesterday our server did not get its daily restart due to players still playing on the server.   The server reset a couple of hours ago and now the bot is working again.  We had the same thing happen last week, but I was unable to see the console log at the time.

I hope this info helps out.

**Comment by GuacaMollee** [comment]
The log actually says the FTP stream lost connection towards the caller. So may have been an FTP issue and not that of SquadJS. If this happens again, try restarting your FTP server.

**Comment by werewolfboy13** [comment]
Closing issue as this outdated, if you are still having issues make a new ticket.
