### ISSUE TITLE
Need a new script(?) for SquadJS

### ISSUE THREAD

**Issue by CrysisDeathgun** [Team-Silver-Sphere/SquadJS#197]
i mean make a kill prompt just like teamkill
who killed who use what
its may help us to trace cheater

**Comment by LeventHAN** [comment]
@CrysisDeathgun I suppose this ticket can be closed?

**Comment by CrysisDeathgun** [comment]
> @CrysisDeathgun I suppose this ticket can be closed?

sure about that thank you
