### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by tcatlas** [Team-Silver-Sphere/SquadJS#2]
Is it possible to use this on Linux? I see node-windows as a dependency in package.json, which I can change to node-linux, but just wondering if there are other things I should look out for.

**Comment by Thomas-Smyth** [comment]
In addition to the dependency, Linux logs appear to be of a different format.

I've discovered this now and am obtaining some sample logs to fix the regexes with.

**Comment by Thomas-Smyth** [comment]
https://github.com/Thomas-Smyth/SquadJS/pull/3
