### ISSUE TITLE
Mapvote CAF Manic 5

### ISSUE THREAD

**Issue by IgnisAlienus** [Team-Silver-Sphere/SquadJS#20]
### Description of Issue
When Mapvoting for CAF Manic RAAS v1 the bot will take it as the winner and announce it as the winner but will not set it as the next map at all.  Admins are manually setting it if this map wins.

### Squad Information
 * SquadJS Version: Most recent 1.0.9
 * Squad Version: Most recent b19.5

### System Information - don't have access to this exact info at this time but are all running most recent on a Windows server
 * Operating System: Windows Server
 * NodeJS Version: Most recent
 * Yarn Version: Most recent

**Comment by Thomas-Smyth** [comment]
It should be fixed in SquadJS v1.0.11.
