### ISSUE TITLE
Mapvote Tallil Tanks

### ISSUE THREAD

**Issue by IgnisAlienus** [Team-Silver-Sphere/SquadJS#26]
### Description of Issue
Mapvote issues for Tallil Tanks using the did you mean method. When voting for tanks v1 or v2 on Tallil we get a return of 'cannot read property 'max' of undefined' from the SquadJS bot

### Errors or Screenshots of Issue
![image](https://user-images.githubusercontent.com/48072845/85190104-9728a900-b27a-11ea-8e72-77f7a972eb90.png)

### Squad Information
 * Plugins in Use: Mapvote did you mean method
 * SquadJS Version: Most recent
 * Squad Version: Most recent b19.5

### System Information
 * Operating System: Windows
 * NodeJS Version: most recent
 * Yarn Version: most recent

**Comment by bumbummen99** [comment]
Seems like the data object for key `estimatedSuitablePlayerCount` is missing:
https://github.com/Thomas-Smyth/SquadJS/blob/d401ee356158389584790908ae1fcfecb54718ec/connectors/data/layers.json#L3779
https://github.com/Thomas-Smyth/SquadJS/blob/d401ee356158389584790908ae1fcfecb54718ec/connectors/squad-layer-filter.js#L269

**Comment by Thomas-Smyth** [comment]
Yeah [my script](https://github.com/Thomas-Smyth/squad-layers/blob/master/updater/get-estimated-suitable-player-count.js) for calculating these figures doesn't handle tank the gamemode... I guess I never thought about adding it.

What player count (min and max) do you think would be suitable for these layers?

**Comment by bumbummen99** [comment]
So i asked our MapRotation guy and he said he would go with something like min 54 and max 80 Players for public map votes, similar to AAS or RAAS.

**Comment by Thomas-Smyth** [comment]
Fixed in SquadJS v1.0.12: https://github.com/Thomas-Smyth/SquadJS/releases/tag/v1.0.12
