### ISSUE TITLE
Mapvote Features

### ISSUE THREAD

**Issue by blackflash01** [Team-Silver-Sphere/SquadJS#29]
> #Mapvote
> 
> * Add option Timer ( vote duration )
> * Add option Ticket ( end of voting when a minimum number of tickets has been issued and reaches  )
> * pick in a discord channel the predefined votes
> * announcement of the current vote every x seconds

**Comment by Thomas-Smyth** [comment]
- [ ] Improve map vote winner notices.
 - [ ] Add map vote timer.
 - [ ] Add ability to control map votes over Discord.

Unfortunately, the ticket suggestion is not possible as ticket counts are not easily accessible via A2S / RCON. Trying to calculate them manually will be very difficult, hard to maintain, and will probably not be very accurate. I've sent a request to OWI for them to add it, so we'll wait and see.

The last suggestion about map voting controls over Discord I will certainly consider, but might not prioritize. Unfortunately, if I was to implement every single possible combination of map voting systems people requested I'd be working on it 24/7. Someone made another suggestion to me which would require quite a bit of refactoring to map votes so I will see if I can find a suitable way to add it when I look into that.

**Comment by Thomas-Smyth** [comment]
Squad v2 makes this irrelevant now.
