### ISSUE TITLE
Mapvote 123 AdminBroadcast

### ISSUE THREAD

**Issue by mattjefferson** [Team-Silver-Sphere/SquadJS#31]
### What is the issue, e.g. map voting, you would like to solve?

- [ ] Would like the map choices to be broadcast via AdminBroadcast

### How would you like us to solve this issue?
Would be nice to cut out the ‘!mapvote help’ step for 123 voting plugin.   Ideally it would broadcast every X minutes until the vote is stopped.  Would probably have to limit the number of map choices to 3 though.

**Comment by Thomas-Smyth** [comment]
Added to beta branch ready for next release. I'd appreciate any feedback on the formatting of the broadcasts.
