### ISSUE TITLE
discord-chat-admin-request || Anti-spam requests

### ISSUE THREAD

**Issue by SiDronee** [Team-Silver-Sphere/SquadJS#33]
discord-chat-admin-request

the command can be used multiple times in a short time resulting in a discord spam, also pinging the admins multiple times.

=====
Add option to change time before sending a new message for the same user:
- make it a plug-in option so that everyone can set their own desired time.

**Comment by Thomas-Smyth** [comment]
Added to beta branch ready for next release.
