### ISSUE TITLE
Feature Request - Rcon built in discord

### ISSUE THREAD

**Issue by GonzLife** [Team-Silver-Sphere/SquadJS#39]
Is it possible to have a rcon sender from discord with this plugin. 
So you can send commands from discord to the server, kick, ban, broadcast, teamswitch and so on ?

**Comment by Thomas-Smyth** [comment]
Added to beta branch ready for next release.

![425a9859bac7618f0834d8238cb215c1](https://user-images.githubusercontent.com/26906760/89100038-d30f6c00-d3eb-11ea-955c-fdf49149e24c.png)
