### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by sfc9982** [Team-Silver-Sphere/SquadJS#4]
I have install the requirements.
But I got
`import Server from 'squad-server';
SyntaxError: Cannot use import statement outside a module`
Error, I tried to use babel or it's unable to use 'import' function.
Could you tell me how you config your enviroment, I am a very new guy to Node.JS.
Forgive me for my rashness, thank you.

**Comment by Thomas-Smyth** [comment]
What Node.js version are you using?

**Comment by sfc9982** [comment]
> What Node.js version are you using?

I have tried 12.16.1 and 12.10.0

**Comment by Thomas-Smyth** [comment]
Please ensure you follow the guidance in the readme. 

The current Nodejs version is needed, which is 13.12.0. It can be downloaded [here](https://nodejs.org/en/).
