### ISSUE TITLE
Discord RCON Improvements

### ISSUE THREAD

**Issue by Thomas-Smyth** [Team-Silver-Sphere/SquadJS#42]
### What is the issue, e.g. map voting, you would like to solve?
Improvements to Discord RCON.

### How would you like us to solve this issue?
* Have an autocorrect for the maps for map commands.
* Have roles to give/limit access to certain commands.

**Comment by SeanWalsh95** [comment]
> - Have roles to give/limit access to certain commands.

addressed in PR(#85)
