### ISSUE TITLE
Mapvote Albasrah RCON command incorrect

### ISSUE THREAD

**Issue by got2bhockey** [Team-Silver-Sphere/SquadJS#46]
### Description of Issue
When voting for CAF_Albasrah_Invasion_v1 the rcon command should have a space between Al and Basrah. Not sure if any of the other layers on this CAF rotation have this issue, just noticed it for this single one.

### Squad Information
 * Plugins in Use: mapvote didyoumean
 * SquadJS Version: latest master
 * Squad Version: 21.1

**Comment by Thomas-Smyth** [comment]
Fixed in SquadJS v1.3.1: https://github.com/Thomas-Smyth/SquadJS/commit/f5e5acee51aa6b9bfca7140865aa4270dcd344a2
