### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8086

### ISSUE THREAD

**Issue by tcatlas** [Team-Silver-Sphere/SquadJS#5]
I am getting this error when I run SquadJS via `node index.js`

```
(node:24761) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:8086
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
(node:24761) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 19)
```
&nbsp;
&nbsp;
> index.js

```
import Server from 'squad-server';

import {
  discordTeamkill
} from 'plugins';

async function main() {
  const server = new Server({
    id: 0,

    host: 'xxx',
    rconPort: 21114,
    rconPassword: 'xxx',
    logDir: '/home/squadserver/serverfiles/SquadGame/Saved/Logs/'
  });

  // discord logging
  await discordTeamkill(
  server, 
  '695055571639861268', 
    { // options
      color: 15844367 // color of embed
    }
  );

  await server.watch();
}

main();
```
- For host I had to put in my actual IP address. The localhost address doesn't work, says connection refused. 
- Discord login token is configured in `core/config.js`, and the bot shows as online on my Discord server.
- This is on Ubuntu 18.04.
- Running latest node as of yesterday.

**Comment by tcatlas** [comment]
I see 8086 is the port for InfluxDB, but I don't have that set up in my `index.js` as you can see above.

Also, since I never actually stated my issue, teamkills aren't being logged to the provided Discord channel.

**Comment by xCausxn** [comment]
As a temporary workaround for the InfluxDB Issue "if you are not wanting to use influxDB"

Open `plugins/index.js` and comment out `influxdbLog`

**Comment by tcatlas** [comment]
Must be some other issue, still not seeing teamkills in Discord.

**Comment by Thomas-Smyth** [comment]
Thank you for highlighting the InfluxDB connection error... someone messaged it to me previously but I forgot about it. That has now been fixed, so you should pull these changes if you're not using the InfluxDB plugin to prevent that error from occurring.

If teamkills notifications are not working, can you please check the following:
 * Teamkill logging is enabled in the Squad server `Engine.ini` file.
 * Teamkills are being logged in your `SquadGame.log` file by searching for `TeamKill`.
 * You have the latest SquadJS version installed. Linux support, which fixed teamkill logging not working on the OS amongst other things, only just got released the other day.

**Comment by tcatlas** [comment]
Yeah teamkills aren't being logged for some reason even though I have enabled it in Engine.ini. I'll see if I can figure out why (and yes I've restarted the server).

I'd say the issue at hand here is resolved though, I no longer get the influxdb error with the latest SquadJS code.
