### ISSUE TITLE
Seed time = Skirmish maps

### ISSUE THREAD

**Issue by PolTville** [Team-Silver-Sphere/SquadJS#50]
Hi!

A system that launches maps only in Skirmish mode for a small number of people on the server.
And which launches the map rotation when the server have a certain number of users.

Amazing Job,
Paul

**Comment by FierceTerrity** [comment]
I agree, a very useful function.

I think everyone would benefit from the !skipmap function.

**Comment by Thomas-Smyth** [comment]
There is now a seeding gamemode in the core game making this issue no longer necessary.

Sorry for not implementing this sooner. Thank you for the suggestion.
