### ISSUE TITLE
New !mapvote mode

### ISSUE THREAD

**Issue by FierceTerrity** [Team-Silver-Sphere/SquadJS#52]
I suggest adding a third voting mode !Mapvote. Аny player on the server can launch it (
if someone has already started voting, then the next time you can start in half an hour.).
After the start, the players are asked to write + or - in the chat, if the voting is recognized as successful, then voting for the map begins (for example, take a list of 10 maps from the local file), and then the players will vote again for a specific card. !1 !2 !3 etc.

**Comment by LuisMartinSchick** [comment]
So, am I understanding this correctly?
The plugin is started by anybody typing in `!mapvote`.
Then, people need to vote to accept the mapvote via `+` or `-`.
If the vote is succesful, players need to choose between different maps? And these maps are saved in the config?

**Comment by Thomas-Smyth** [comment]
Squad v2 makes this irrelevant now.
