### ISSUE TITLE
discord-round-winner || Add score

### ISSUE THREAD

**Issue by SiDronee** [Team-Silver-Sphere/SquadJS#72]
PLUGIN: discord-round-winner
Extra feature request info: 

When a match has been played, a screenshot is often taken and shared in the discord channel. It would be nice if the discord-round-winner plugin didn't just indicate who won in which match. But also a table drops with there score. I dont mind dropping the hole scoreboard but if discord doesnt allow it can we have a filter that we can say:  show top 10 (and have the option to change that in the config).  Also an option filter on prio, so in the config filterprio: KD, points , etc... 

So it is 2 tables next to each other

Party 1                                         | Party 2
Name | KD | D | K | R | POINTS    | Name | KD | D | K | R | POINTS

**Comment by IgnisAlienus** [comment]
Final Ticket counts are a goal for me with the Round Winner plugin. I do like adding those options to show more details, it just will be difficult with the way the squadlog.log currently logs some of this stuff. I had a Dev mention that logs are getting updated at v1.2 so that they provide more information.

**Comment by Thomas-Smyth** [comment]
```
fabsther 03/12/2020
"Team %d, %s ( %s ) has won the match with %d Tickets on layer %s (level %s)!"), WinningTeamID, *WinningTeamFactionSetup, *WinningTeamFaction, WinningTickets, *LayerName, *LevelName));
"Team %d, %s ( %s ) has lost the match with %d Tickets on layer %s (level %s)!"), LosingTeamID, *LosingTeamFactionSetup, *LosingTeamFaction, LosingTickets, *LayerName, *LevelName));
```
https://discordapp.com/channels/101469020510773248/340307997479796737/784138320417390654

Possibly in Squad v2.

**Comment by Thomas-Smyth** [comment]
The above was added. However, it's currently only logged in the in-game console, we'll have to wait until it's added to the server logs or RCON before we can make use of it.

**Comment by ect0s** [comment]
Closing with merged  of patch

https://github.com/Team-Silver-Sphere/SquadJS/pull/256
