### ISSUE TITLE
Plugin: discord-admin-request, support multiple admin prefixes

### ISSUE THREAD

**Issue by got2bhockey** [Team-Silver-Sphere/SquadJS#74]
### What is the issue, e.g. map voting, you would like to solve?
Since Caps Lock is bound to a key within game, we often see admin reports coming in as !ADMIN. Since the admin-request plugin only looks for !admin (case sensitive), these all caps admin requests are not forwarded into our discord channel.

### How would you like us to solve this issue?
This could be solved by either making the detection for !admin non-case-sensitive or by making the "adminPrefix" config entry support multiple admin commands (e.g: !admin, !ADMIN).

**Comment by LeventHAN** [comment]
The issue should be fixed now if there aren't any issues with my pull: https://github.com/Thomas-Smyth/SquadJS/pull/78

**Comment by 11TStudio** [comment]
#78

**Comment by Thomas-Smyth** [comment]
Cases sensitivity resolved in v2.
