### ISSUE TITLE
Incorrect Time | Logs local time to Mysql DB

### ISSUE THREAD

**Issue by IPFR33LY** [Team-Silver-Sphere/SquadJS#87]
Hello. I'll make this short and sweet.

index.js has this

```
server.on(PLAYERS_UPDATED, (players) => {
      options.mysqlPool.query(
        'INSERT INTO PlayerCount(time, server, player_count) VALUES (NOW(),?,?)',
        [serverID, players.length]
      );
```

That logs the local time and not correct UTC time.

Therefore; it should be mentioned in the README that it is necessary to set the mysql instance to use UTC time.

![image](https://user-images.githubusercontent.com/6550600/94980427-410d0800-04ef-11eb-92f5-835ec6631ebc.png)

**Comment by Thomas-Smyth** [comment]
mysql-log plugin has been replaced by DBLog plugin, so I will close this.
